=== Orange-hanter/Marvie/Software/Xml/schemas/SensorData.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="name">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:pattern value="[0-9A-Za-z_]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:attribute name="bias">
    <xs:simpleType>
      <xs:restriction base="xs:int">
        <xs:minInclusive value="0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="count">
    <xs:simpleType>
      <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>
  </xs:attribute>

  <xs:element name="char">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="int8">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="uint8">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="int16">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="uint16">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="int32">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="uint32">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="int64">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="uint64">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="float">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="double">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="name">
          <xs:attribute ref="bias"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:group name="basicTypesGroup">
    <xs:choice>
      <xs:element ref="char"/>
      <xs:element ref="int8"/>
      <xs:element ref="uint8"/>
      <xs:element ref="int16"/>
      <xs:element ref="uint16"/>
      <xs:element ref="int32"/>
      <xs:element ref="uint32"/>
      <xs:element ref="int64"/>
      <xs:element ref="uint64"/>
      <xs:element ref="float"/>
      <xs:element ref="double"/>
    </xs:choice>
  </xs:group>

  <xs:group name="auxGroup">
    <xs:sequence>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:group ref="basicTypesGroup"/>
        <xs:element name="unused">
          <xs:complexType>
            <xs:attribute name="size" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:int">
                  <xs:minInclusive value="1"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="array">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="name">
                <xs:attribute name="type" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="char"/>
                      <xs:enumeration value="int8"/>
                      <xs:enumeration value="uint8"/>
                      <xs:enumeration value="int16"/>
                      <xs:enumeration value="uint16"/>
                      <xs:enumeration value="int32"/>
                      <xs:enumeration value="uint32"/>
                      <xs:enumeration value="int64"/>
                      <xs:enumeration value="uint64"/>
                      <xs:enumeration value="float"/>
                      <xs:enumeration value="double"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute ref="count" use="required"/>
                <xs:attribute ref="bias" use="optional"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="groupArray">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="group" type="group" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute ref="count" use="required"/>
            <xs:attribute ref="bias" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="group" type="group"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>

  <xs:complexType name="group">
    <xs:group ref="auxGroup"/>
    <xs:attribute name="name" type="name" use="required"/>
  </xs:complexType>

  <xs:element name="DataDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="auxGroup" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="size" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Orange-hanter/Marvie/Software/Sensors/SimpleSensor/DataDesc.xml
<?xml version="1.0"?>
<DataDesc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:// ../../Xml/schemas/SensorData.xsd">
  <int32>a</int32>
  <array type="float" bias="8" count="3">b</array>
  <unused size="4"/>
  <double>d</double>
  <groupArray count="2">
    <group name="Ch">
      <int8>c</int8>
      <array type="char" count="3">str</array>
      <array type="uint16" count="2">m</array>
      <unused size="4"/>
    </group>
  </groupArray>
</DataDesc>

=== Orange-hanter/Marvie/Software/Sensors/TEM104/DataDesc.xml
<?xml version="1.0"?>
<DataDesc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:// ../../Xml/schemas/SensorData.xsd">
  <group name="Instant">
    <groupArray count="4">
      <group name="Channel">
        <array type="float" count="4">tmp</array>
        <array type="float" count="4">prs</array>
        <array type="float" count="4">ro</array>
        <array type="float" count="4">hent</array>
        <array type="float" count="4">rshv</array>
        <array type="float" count="4">rshm</array>
        <array type="float" count="4">pwr</array>
        <uint8>tekerr</uint8>
        <unused size="1"/>
        <uint16>teherr</uint16>
      </group>
    </groupArray>
  </group>
 
  <group name="Integrated">
    <array type="uint8" count="4">date</array>
    <array type="uint8" count="4">prevDate</array>
    <uint32>TRab</uint32>
    <unused size="4"/>
    <groupArray count="4">
      <group name="Channel">
        <double>intV</double>
        <double>intM</double>
        <double>intQ</double>
        <uint32>TNar</uint32>
        <uint32>Tmin</uint32>
        <uint32>Tmax</uint32>
        <uint32>Tdt</uint32>
        <uint32>Ttn</uint32>
        <uint16>teherr</uint16>
        <uint8>tekerr</uint8>
        <unused size="1"/>
        <array type="uint16" count="3" >t</array>
        <unused size="2"/>
        <array type="uint8" count="3">p</array>
        <unused size="1"/>
        <float>rshv</float>
      </group>
    </groupArray>
  </group>
</DataDesc>

=== Orange-hanter/Marvie/Software/Sensors/TERM0208/DataDesc.xml
<?xml version="1.0"?>
<DataDesc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:// ../../Xml/schemas/SensorData.xsd">
  <group name="Instant">
    <array type="float" count="3">G</array>
    <array type="float" count="3">M</array>
    <array type="int32" count="2">Q</array>
    <array type="float" count="4">t</array>
    <array type="float" count="4">p</array>
    <array type="uint8" count="4">err</array>
    <unused size="4"/>
  </group>
  <group name="Integrated">
    <array type="double" count="3">G</array>
    <array type="double" count="3">M</array>
    <array type="uint64" count="2">Q</array>
    <array type="uint32" count="2">timeWork</array>
    <array type="uint32" count="2">timeErr</array>
    <group name="PerHour">
      <array type="double" count="3">V</array>
      <array type="double" count="3">M</array>
      <array type="uint64" count="2">Q</array>
      <array type="uint8" count="4">err</array>
      <unused size="4"/>
    </group>
    <group name="PerDay">
      <array type="double" count="3">V</array>
      <array type="double" count="3">M</array>
      <array type="uint64" count="2">Q</array>
      <array type="uint8" count="4">err</array>
      <unused size="4"/>
    </group>
  </group>
</DataDesc>

=== Orange-hanter/Marvie/Software/Sensors/TEM104M2/DataDesc.xml
<?xml version="1.0"?>
<DataDesc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:// ../../Xml/schemas/SensorData.xsd">
  <group name="Instant">
    <groupArray count="4">
      <group name="Channel">
        <array type="float" count="4">tmp</array>
        <array type="float" count="4">prs</array>
        <array type="float" count="4">ro</array>
        <array type="float" count="4">hent</array>
        <array type="float" count="4">rshv</array>
        <array type="float" count="4">rshm</array>
        <array type="float" count="4">pwr</array>
      </group>
    </groupArray>
  </group>
 
 <group name="Integrated">
    <uint32>T_Rab</uint32>
    <uint32>T_offline</uint32>
    <groupArray count="4">
      <group name="Channel">
        <double>intV</double>
        <double>intM</double>
        <double>intQ</double>
        <double>intQErr</double>
        <uint32>T_Nar</uint32>
        <uint32>T_Max</uint32>
        <uint32>T_Min</uint32>
        <uint32>T_dt</uint32>
        <uint32>T_tn</uint32>
        <uint32>T_rev</uint32>
        <uint32>T_pt</uint32>
        <uint8>tekerr</uint8>
        <uint8>teherr</uint8>
        <array type="uint16" count="3" >t</array>
        <array type="uint16" count="3">p</array>
      </group>
    </groupArray>
  </group>
</DataDesc>

=== Orange-hanter/Marvie/Software/Sensors/TERM0204/DataDesc.xml
<?xml version="1.0"?>
<DataDesc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:// ../../Xml/schemas/SensorData.xsd">
  <group name="Instant">
    <groupArray count="2">
      <group name="Channel">
        <float>G</float>
        <float>P</float>
        <float>tmpSupply</float>
        <float>tmpReturn</float>
      </group>
    </groupArray>
    <float>pSupply</float>
    <float>pReturn</float>
    <float>vAdditional</float>
    <uint16>error</uint16>
    <unused size="2"/>
  </group>

  <group name="Integrated">
    <groupArray count="2">
      <group name="Channel">
        <float>vSumm</float>
        <float>mSumm</float>
        <float>QSumm</float>
      </group>
    </groupArray>
    <float>vSummAdditional</float>
  </group>
</DataDesc>

=== Orange-hanter/Marvie/Software/Sensors/TEM05M/DataDesc.xml
<?xml version="1.0"?>
<DataDesc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:// ../../Xml/schemas/SensorData.xsd">
  <groupArray count="2">
    <group name="Channel">
      <float>G</float>
      <float>P</float>
      <float>Q</float>
      <float>V</float>
      <float>M</float>
      <float>t</float>
    </group>
  </groupArray>
  <float>tCW</float>
  <uint32>error</uint32>
</DataDesc>

=== Orange-hanter/Marvie/Software/Sensors/TEM104U/DataDesc.xml
<?xml version="1.0"?>
<DataDesc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:// ../../Xml/schemas/SensorData.xsd">
  <group name="Instant">
    <float>rshv</float>
    <float>rshm</float>
    <array type="float" count="2">tmp</array>
    <array type="float" count="2">prs</array>
  </group>
 
  <group name="Integrated">
    <double>intV</double>
    <double>intM</double>
    <double>intQ</double>
    <uint32>T_Wrk</uint32>
    <uint32>T_Cnt</uint32>
    <uint32>T_Fail</uint32>
    <uint32>T_Dt</uint32>
    <uint32>T_Gmax</uint32>
    <uint32>T_Gmin</uint32>
    <array type="uint16" count="2">tmp</array>
    <array type="uint8" count="2">prs</array>
    <uint8>TekErr</uint8>
    <uint8>TehErr</uint8>
  </group>
</DataDesc>
